# Correction pour une structure plate (tous les fichiers au même niveau)
add_executable(Akropolis
        main.cpp
        Cite.cpp
        CoordHex.cpp
        GameExcep_Enums.cpp
        HexCons_Carr_Quart_Place.cpp
        Joueur.cpp
        Partie_Variante.cpp
        Pioche_ChoixTuile.cpp
        Score.cpp
        TuileCite_TuileDep.cpp
        Type.cpp
        fabrique_tuiles.cpp
)